## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
dist: xenial
os: linux
julia:
  - 1.1
notifications:
  email: false
git:
  depth: 99999999

after_success:
  # push coverage results to Coveralls
  - julia -e 'import Pkg; cd(Pkg.dir("TrackingHeaps")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'import Pkg; cd(Pkg.dir("TrackingHeaps")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  include:
    - stage: Documentation
      julia: 1.1
      os: linux
      dist: xenial
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs --color=yes docs/make.jl
      after_success: skip

